//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tArchivosPaciente
    {
        public int idArchivo { get; set; }
        public int idPaciente { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public byte[] Archivo { get; set; }
        public System.DateTime FechaSubida { get; set; }
    
        public virtual tPacientes tPacientes { get; set; }
    }
}
