//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCalificacion
    {
        public int idCalificacion { get; set; }
        public int idPaciente { get; set; }
        public string Comentario { get; set; }
        public int Estrellas { get; set; }
    
        public virtual tPacientes tPacientes { get; set; }
    }
}
