//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHistoriaCE
    {
        public int idExpediente { get; set; }
        public int idPaciente { get; set; }
        public string Diagnostico { get; set; }
        public string Procedimiento { get; set; }
        public string Medicacion { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public byte[] Archivos { get; set; }
    
        public virtual tPacientes tPacientes { get; set; }
    }
}
