//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHistoriaCE
    {
        public int idExpediente { get; set; }
        public int idPaciente { get; set; }
        public string Diagnostico { get; set; }
        public string Procedimiento { get; set; }
        public string Medicacion { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public byte[] Archivos { get; set; }
    
        public virtual tPacientes tPacientes { get; set; }
    }
}
