//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrdenesProductos
    {
        public int idOrdenProducto { get; set; }
        public int idOrdenCompra { get; set; }
        public int idProducto { get; set; }
        public int CantidadSolicitada { get; set; }
    
        public virtual tInventario tInventario { get; set; }
        public virtual tOrdenesCompra tOrdenesCompra { get; set; }
    }
}
