//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrdenesCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrdenesCompra()
        {
            this.tOrdenesProductos = new HashSet<tOrdenesProductos>();
        }
    
        public int idOrdenCompra { get; set; }
        public int idProveedor { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string EstadoOrden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrdenesProductos> tOrdenesProductos { get; set; }
        public virtual tProveedores tProveedores { get; set; }
    }
}
