//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductosTratamiento
    {
        public int idProductoTratamiento { get; set; }
        public int idProducto { get; set; }
        public int idCita { get; set; }
        public int CantidadUtilizada { get; set; }
    
        public virtual tCitas tCitas { get; set; }
        public virtual tInventario tInventario { get; set; }
    }
}
