//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRecomendacionesProducto
    {
        public int idRecomendacion { get; set; }
        public int idSeguimiento { get; set; }
        public string RecomendacionTexto { get; set; }
    
        public virtual tSeguimientoProducto tSeguimientoProducto { get; set; }
    }
}
