//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRecomendacionesProducto
    {
        public int idRecomendacion { get; set; }
        public int idSeguimiento { get; set; }
        public string RecomendacionTexto { get; set; }
    
        public virtual tSeguimientoProducto tSeguimientoProducto { get; set; }
    }
}
