//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSeguimientoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSeguimientoProducto()
        {
            this.tRecomendacionesProducto = new HashSet<tRecomendacionesProducto>();
        }
    
        public int idSeguimiento { get; set; }
        public int idPaciente { get; set; }
        public int idProducto { get; set; }
        public Nullable<System.DateTime> FechaEntregaEstimada { get; set; }
        public string Estado { get; set; }
    
        public virtual tInventario tInventario { get; set; }
        public virtual tPacientes tPacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecomendacionesProducto> tRecomendacionesProducto { get; set; }
    }
}
