//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeGraduacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSeguimientoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSeguimientoProducto()
        {
            this.tRecomendacionesProducto = new HashSet<tRecomendacionesProducto>();
        }
    
        public int idSeguimiento { get; set; }
        public int idPaciente { get; set; }
        public int idProducto { get; set; }
        public Nullable<System.DateTime> FechaEntregaEstimada { get; set; }
        public string Estado { get; set; }
    
        public virtual tInventario tInventario { get; set; }
        public virtual tPacientes tPacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRecomendacionesProducto> tRecomendacionesProducto { get; set; }
    }
}
